/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import picocli.CommandLine;
import picocli.CommandLine.Option;
import picocli.CommandLine.Command;

import java.util.concurrent.locks.AbstractOwnableSynchronizer;

@Command(
        name = "test",
        description = "Test sorter unit benchmark"
)
public class App implements Runnable {

    @Option(names = {"-i", "--iterations"})
    private Integer iterationsCount = 5000;

    @Option(names = {"-l", "--dataLength"})
    private Integer dataLength = 8000;

    public static void main(String[] args) {
        if (args.length == 0) {
            new App().run();
        } else {
            CommandLine.run(new App(), args);
        }
    }


    @Override
    public void run() {
        SorterUnit<Integer> sorterUnit = new IntegerQuickSorter();
        DataProvider<Integer> dataProvider = new SimpleIntegerDataProvider();
        SorterUnit<Integer> benchmarkSorter = new BenchmarkIntegerSorter();
        TestUnit testUnit = new TestUnit();

        testUnit.test(sorterUnit, benchmarkSorter, dataProvider, dataLength, iterationsCount);
        testUnit.test(benchmarkSorter, benchmarkSorter, dataProvider, dataLength, iterationsCount);
        testUnit.test(benchmarkSorter, sorterUnit, dataProvider, dataLength, iterationsCount);
    }
}
