/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import picocli.CommandLine;
import picocli.CommandLine.Option;

public class App implements Runnable {

    @Option(names = {"-i", "--iterations"})
    private int iterationsCount;

    @Option(names = {"-l", "--dataLength"})
    private int dataLength;

    public static void main(String[] args) {
        CommandLine.run(new App(), args);
    }


    @Override
    public void run() {
        SorterUnit<Integer> sorterUnit = new IntegerQuickSorter();
        DataProvider<Integer> dataProvider = new SimpleIntegerDataProvider();
        SorterUnit<Integer> benchmarkSorter = new BenchmarkIntegerSorter();
        TestUnit testUnit = new TestUnit();

        testUnit.test(sorterUnit, benchmarkSorter, dataProvider, dataLength, iterationsCount);
        testUnit.test(benchmarkSorter, benchmarkSorter, dataProvider, dataLength, iterationsCount);
        testUnit.test(benchmarkSorter, sorterUnit, dataProvider, dataLength, iterationsCount);
    }
}
